#**What is Web Scraping**
- Web scraping is the automated process of extracting data from websites by sending requests to:
- Web pages,
- Retrieving their HTML/JSON/XML content, and
- then parsing and converting the required information into a structured format (like CSV, Excel, database, or DataFrame) for analysis or reuse.

#**Steps**

# Step 1:
1. Import libraries

In [ ]:
import time
import pandas as pd
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# time → Provides time-related functions like delays, timestamps, and performance measurement.
# pandas (pd) → A powerful library for data manipulation and analysis, especially with DataFrames.
# requests → Used to send HTTP requests and fetch web content (HTML, JSON, etc.).
# BeautifulSoup (from bs4) → Parses HTML/XML documents to extract structured data.
# urllib.parse (urljoin) → Helps handle and combine URLs correctly.

#**Step 2:**
Choose target website, send an HTTP request to the page (using requests or similar).

In [ ]:
# webpage=requests.get('https://books.toscrape.com/')

In [ ]:
# webpage=requests.get('https://books.toscrape.com/')
# STEP 2: Request the page
URL = "https://books.toscrape.com/"
headers = {"User-Agent": "Mozilla/5.0 (compatible; scraping-tutorial/1.0)"}
resp = requests.get(URL, headers=headers, timeout=30)
resp.raise_for_status()          # will throw if status != 200#

In [ ]:
webpage=requests.get('https://books.toscrape.com/')
webpage

# Step 3:
Parse the HTML response with a parser like BeautifulSoup or lxml

In [ ]:
# STEP 3: Parse HTML
soup = BeautifulSoup(resp.text, "html.parser")
# soup

In [ ]:
soup.find_all('h1')[0].text

'All products'

In [ ]:
# soup.find_all('p')[0].text

In [ ]:
for p in soup.find_all("p"):
    text = p.get_text(strip=True)   # removes whitespace/newlines
    if text:   # print only non-empty text
        print(text)

Â£51.77
In stock
Â£53.74
In stock
Â£50.10
In stock
Â£47.82
In stock
Â£54.23
In stock
Â£22.65
In stock
Â£33.34
In stock
Â£17.93
In stock
Â£22.60
In stock
Â£52.15
In stock
Â£13.99
In stock
Â£20.66
In stock
Â£17.46
In stock
Â£52.29
In stock
Â£35.02
In stock
Â£57.25
In stock
Â£23.88
In stock
Â£37.59
In stock
Â£51.33
In stock
Â£45.17
In stock

In [ ]:
# lenght of books per  page
len(soup.find_all('div', class_="image_container"))

20

In [ ]:
# # lengths of books in  website
base_url = "https://books.toscrape.com/catalogue/page-{}.html"

# # Loop through pages 1 to 50
for page in range(1, 51):
    url = base_url.format(page)
    resp = requests.get(url, timeout=30)

    if resp.status_code == 200:
        soup = BeautifulSoup(resp.text, "html.parser")
        containers = soup.find_all("div", class_="image_container")
        print(f"Page {page}: Found {len(containers)} image_container")
    else:
        print(f"Page {page}: Failed to fetch (status {resp.status_code})")

Page 1: Found 20 image_container
Page 2: Found 20 image_container
Page 3: Found 20 image_container
Page 4: Found 20 image_container
Page 5: Found 20 image_container
Page 6: Found 20 image_container
Page 7: Found 20 image_container
Page 8: Found 20 image_container
Page 9: Found 20 image_container
Page 10: Found 20 image_container
Page 11: Found 20 image_container
Page 12: Found 20 image_container
Page 13: Found 20 image_container
Page 14: Found 20 image_container
Page 15: Found 20 image_container
Page 16: Found 20 image_container
Page 17: Found 20 image_container
Page 18: Found 20 image_container
Page 19: Found 20 image_container
Page 20: Found 20 image_container
Page 21: Found 20 image_container
Page 22: Found 20 image_container
Page 23: Found 20 image_container
Page 24: Found 20 image_container
Page 25: Found 20 image_container
Page 26: Found 20 image_container
Page 27: Found 20 image_container
Page 28: Found 20 image_container
Page 29: Found 20 image_container
Page 30: Found 20 image_container
Page 31: Found 20 image_container
Page 32: Found 20 image_container
Page 33: Found 20 image_container
Page 34: Found 20 image_container
Page 35: Found 20 image_container
Page 36: Found 20 image_container
Page 37: Found 20 image_container
Page 38: Found 20 image_container
Page 39: Found 20 image_container
Page 40: Found 20 image_container
Page 41: Found 20 image_container
Page 42: Found 20 image_container
Page 43: Found 20 image_container
Page 44: Found 20 image_container
Page 45: Found 20 image_container
Page 46: Found 20 image_container
Page 47: Found 20 image_container
Page 48: Found 20 image_container
Page 49: Found 20 image_container
Page 50: Found 20 image_container

In [ ]:
soup.find_all('h3')

[<h3><a href="frankenstein_20/index.html" title="Frankenstein">Frankenstein</a></h3>,
 <h3><a href="forever-rockers-the-rocker-12_19/index.html" title="Forever Rockers (The Rocker #12)">Forever Rockers (The Rocker ...</a></h3>,
 <h3><a href="fighting-fate-fighting-6_18/index.html" title="Fighting Fate (Fighting #6)">Fighting Fate (Fighting #6)</a></h3>,
 <h3><a href="emma_17/index.html" title="Emma">Emma</a></h3>,
 <h3><a href="eat-pray-love_16/index.html" title="Eat, Pray, Love">Eat, Pray, Love</a></h3>,
 <h3><a href="deep-under-walker-security-1_15/index.html" title="Deep Under (Walker Security #1)">Deep Under (Walker Security ...</a></h3>,
 <h3><a href="choosing-our-religion-the-spiritual-lives-of-americas-nones_14/index.html" title="Choosing Our Religion: The Spiritual Lives of America's Nones">Choosing Our Religion: The ...</a></h3>,
 <h3><a href="charlie-and-the-chocolate-factory-charlie-bucket-1_13/index.html" title="Charlie and the Chocolate Factory (Charlie Bucket #1)">Charlie and the Chocolate ...</a></h3>,
 <h3><a href="charitys-cross-charles-towne-belles-4_12/index.html" title="Charity's Cross (Charles Towne Belles #4)">Charity's Cross (Charles Towne ...</a></h3>,
 <h3><a href="bright-lines_11/index.html" title="Bright Lines">Bright Lines</a></h3>,
 <h3><a href="bridget-joness-diary-bridget-jones-1_10/index.html" title="Bridget Jones's Diary (Bridget Jones #1)">Bridget Jones's Diary (Bridget ...</a></h3>,
 <h3><a href="bounty-colorado-mountain-7_9/index.html" title="Bounty (Colorado Mountain #7)">Bounty (Colorado Mountain #7)</a></h3>,
 <h3><a href="blood-defense-samantha-brinkman-1_8/index.html" title="Blood Defense (Samantha Brinkman #1)">Blood Defense (Samantha Brinkman ...</a></h3>,
 <h3><a href="bleach-vol-1-strawberry-and-the-soul-reapers-bleach-1_7/index.html" title="Bleach, Vol. 1: Strawberry and the Soul Reapers (Bleach #1)">Bleach, Vol. 1: Strawberry ...</a></h3>,
 <h3><a href="beyond-good-and-evil_6/index.html" title="Beyond Good and Evil">Beyond Good and Evil</a></h3>,
 <h3><a href="alice-in-wonderland-alices-adventures-in-wonderland-1_5/index.html" title="Alice in Wonderland (Alice's Adventures in Wonderland #1)">Alice in Wonderland (Alice's ...</a></h3>,
 <h3><a href="ajin-demi-human-volume-1-ajin-demi-human-1_4/index.html" title="Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)">Ajin: Demi-Human, Volume 1 ...</a></h3>,
 <h3><a href="a-spys-devotion-the-regency-spies-of-london-1_3/index.html" title="A Spy's Devotion (The Regency Spies of London #1)">A Spy's Devotion (The ...</a></h3>,
 <h3><a href="1st-to-die-womens-murder-club-1_2/index.html" title="1st to Die (Women's Murder Club #1)">1st to Die (Women's ...</a></h3>,
 <h3><a href="1000-places-to-see-before-you-die_1/index.html" title="1,000 Places to See Before You Die">1,000 Places to See ...</a></h3>]

In [ ]:
for i in soup.find_all('h3'):
  print(i.text)

Frankenstein
Forever Rockers (The Rocker ...
Fighting Fate (Fighting #6)
Emma
Eat, Pray, Love
Deep Under (Walker Security ...
Choosing Our Religion: The ...
Charlie and the Chocolate ...
Charity's Cross (Charles Towne ...
Bright Lines
Bridget Jones's Diary (Bridget ...
Bounty (Colorado Mountain #7)
Blood Defense (Samantha Brinkman ...
Bleach, Vol. 1: Strawberry ...
Beyond Good and Evil
Alice in Wonderland (Alice's ...
Ajin: Demi-Human, Volume 1 ...
A Spy's Devotion (The ...
1st to Die (Women's ...
1,000 Places to See ...

In [ ]:
import requests
from bs4 import BeautifulSoup

base_url = "https://books.toscrape.com/catalogue/page-{}.html"

# Loop through pages 1 to 50
for page in range(1, 51):
    url = base_url.format(page)
    resp = requests.get(url, timeout=30)

    if resp.status_code == 200:
        soup = BeautifulSoup(resp.text, "html.parser")
        containers = soup.find_all("h3")

        print(f"\nPage {page}: Found {len(containers)} books")

        # Extract book titles
        for h3 in containers:
            title = h3.find("a")["title"]   # book title is inside the "title" attribute
            print(" -", title)
    else:
        print(f"Page {page}: Failed to fetch (status {resp.status_code})")

Page 1: Found 20 books
 - A Light in the Attic
 - Tipping the Velvet
 - Soumission
 - Sharp Objects
 - Sapiens: A Brief History of Humankind
 - The Requiem Red
 - The Dirty Little Secrets of Getting Your Dream Job
 - The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
 - The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
 - The Black Maria
 - Starving Hearts (Triangular Trade Trilogy, #1)
 - Shakespeare's Sonnets
 - Set Me Free
 - Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
 - Rip it Up and Start Again
 - Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
 - Olio
 - Mesaerion: The Best Science Fiction Stories 1800-1849
 - Libertarianism for Beginners
 - It's Only the Himalayas

Page 2: Found 20 books
 - In Her Wake
 - How Music Works
 - Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More
 - Chase Me (Paris Nights #2)
 - Black Dust
 - Birdsong: A Story in Pictures
 - America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana
 - Aladdin and His Wonderful Lamp
 - Worlds Elsewhere: Journeys Around Shakespeareâs Globe
 - Wall and Piece
 - The Four Agreements: A Practical Guide to Personal Freedom
 - The Five Love Languages: How to Express Heartfelt Commitment to Your Mate
 - The Elephant Tree
 - The Bear and the Piano
 - Sophie's World
 - Penny Maybe
 - Maude (1883-1993):She Grew Up with the country
 - In a Dark, Dark Wood
 - Behind Closed Doors
 - You can't bury them all: Poems

Page 3: Found 20 books
 - Slow States of Collapse: Poems
 - Reasons to Stay Alive
 - Private Paris (Private #10)
 - #HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.
 - Without Borders (Wanderlove #1)
 - When We Collided
 - We Love You, Charlie Freeman
 - Untitled Collection: Sabbath Poems 2014
 - Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness
 - Unicorn Tracks
 - Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink
 - Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2)
 - Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity
 - This One Summer
 - Thirst
 - The Torch Is Passed: A Harding Family Story
 - The Secret of Dreadwillow Carse
 - The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!
 - The Past Never Ends
 - The Natural History of Us (The Fine Art of Pretending #2)

Page 4: Found 20 books
 - The Nameless City (The Nameless City #1)
 - The Murder That Never Was (Forensic Instincts #5)
 - The Most Perfect Thing: Inside (and Outside) a Bird's Egg
 - The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy
 - The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing
 - The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer
 - The Gutsy Girl: Escapades for Your Life of Epic Adventure
 - The Electric Pencil: Drawings from Inside State Hospital No. 3
 - The Death of Humanity: and the Case for Life
 - The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life
 - The Art Forger
 - The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind
 - The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution
 - Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up
 - Soul Reader
 - Security
 - Saga, Volume 6 (Saga (Collected Editions) #6)
 - Saga, Volume 5 (Saga (Collected Editions) #5)
 - Reskilling America: Learning to Labor in the Twenty-First Century
 - Rat Queens, Vol. 3: Demons (Rat Queens (Collected Editions) #11-15)

Page 5: Found 20 books
 - Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)
 - Princess Between Worlds (Wide-Awake Princess #5)
 - Pop Gun War, Volume 1: Gift
 - Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics
 - Patience
 - Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)
 - orange: The Complete Collection 1 (orange: The Complete Collection #1)
 - Online Marketing for Busy Authors: A Step-By-Step Guide
 - On a Midnight Clear
 - Obsidian (Lux #1)
 - My Paris Kitchen: Recipes and Stories
 - Masks and Shadows
 - Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed
 - Lumberjanes, Vol. 2: Friendship to the Max (Lumberjanes #5-8)
 - Lumberjanes, Vol. 1: Beware the Kitten Holy (Lumberjanes #1-4)
 - Lumberjanes Vol. 3: A Terrible Plan (Lumberjanes #9-12)
 - Layered: Baking, Building, and Styling Spectacular Cakes
 - Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners)
 - Join
 - In the Country We Love: My Family Divided

Page 6: Found 20 books
 - Immunity: How Elie Metchnikoff Changed the Course of Modern Medicine
 - I Hate Fairyland, Vol. 1: Madly Ever After (I Hate Fairyland (Compilations) #1-5)
 - I am a Hero Omnibus Volume 1
 - How to Be Miserable: 40 Strategies You Already Use
 - Her Backup Boyfriend (The Sorensen Family #1)
 - Giant Days, Vol. 2 (Giant Days #5-8)
 - Forever and Forever: The Courtship of Henry Longfellow and Fanny Appleton
 - First and First (Five Boroughs #3)
 - Fifty Shades Darker (Fifty Shades #2)
 - Everydata: The Misinformation Hidden in the Little Data You Consume Every Day
 - Don't Be a Jerk: And Other Practical Advice from Dogen, Japan's Greatest Zen Master
 - Danganronpa Volume 1
 - Crown of Midnight (Throne of Glass #2)
 - Codename Baboushka, Volume 1: The Conclave of Death
 - Camp Midnight
 - Call the Nurse: True Stories of a Country Nurse on a Scottish Isle
 - Burning
 - Bossypants
 - Bitch Planet, Vol. 1: Extraordinary Machine (Bitch Planet (Collected Editions))
 - Avatar: The Last Airbender: Smoke and Shadow, Part 3 (Smoke and Shadow #3)

Page 7: Found 20 books
 - Algorithms to Live By: The Computer Science of Human Decisions
 - A World of Flavor: Your Gluten Free Passport
 - A Piece of Sky, a Grain of Rice: A Memoir in Four Meditations
 - A Murder in Time
 - A Flight of Arrows (The Pathfinders #2)
 - A Fierce and Subtle Poison
 - A Court of Thorns and Roses (A Court of Thorns and Roses #1)
 - (Un)Qualified: How God Uses Broken People to Do Big Things
 - You Are What You Love: The Spiritual Power of Habit
 - William Shakespeare's Star Wars: Verily, A New Hope (William Shakespeare's Star Wars #4)
 - Tuesday Nights in 1980
 - Tracing Numbers on a Train
 - Throne of Glass (Throne of Glass #1)
 - Thomas Jefferson and the Tripoli Pirates: The Forgotten War That Changed American History
 - Thirteen Reasons Why
 - The White Cat and the Monk: A Retelling of the Poem âPangur BÃ¡nâ
 - The Wedding Dress
 - The Vacationers
 - The Third Wave: An Entrepreneurâs Vision of the Future
 - The Stranger

Page 8: Found 20 books
 - The Shadow Hero (The Shadow Hero)
 - The Secret (The Secret #1)
 - The Regional Office Is Under Attack!
 - The Psychopath Test: A Journey Through the Madness Industry
 - The Project
 - The Power of Now: A Guide to Spiritual Enlightenment
 - The Omnivore's Dilemma: A Natural History of Four Meals
 - The Nerdy Nummies Cookbook: Sweet Treats for the Geek in All of Us
 - The Murder of Roger Ackroyd (Hercule Poirot #4)
 - The Mistake (Off-Campus #2)
 - The Matchmaker's Playbook (Wingmen Inc. #1)
 - The Love and Lemons Cookbook: An Apple-to-Zucchini Celebration of Impromptu Cooking
 - The Long Shadow of Small Ghosts: Murder and Memory in an American City
 - The Kite Runner
 - The House by the Lake
 - The Glittering Court (The Glittering Court #1)
 - The Girl on the Train
 - The Genius of Birds
 - The Emerald Mystery
 - The Cookies & Cups Cookbook: 125+ sweet & savory recipes reminding you to Always Eat Dessert First

Page 9: Found 20 books
 - The Bridge to Consciousness: I'm Writing the Bridge Between Science and Our Old and New Beliefs.
 - The Artist's Way: A Spiritual Path to Higher Creativity
 - The Art of War
 - The Argonauts
 - The 10% Entrepreneur: Live Your Startup Dream Without Quitting Your Day Job
 - Suddenly in Love (Lake Haven #1)
 - Something More Than This
 - Soft Apocalypse
 - So You've Been Publicly Shamed
 - Shoe Dog: A Memoir by the Creator of NIKE
 - Shobu Samurai, Project Aryoku (#3)
 - Secrets and Lace (Fatal Hearts #1)
 - Scarlett Epstein Hates It Here
 - Romero and Juliet: A Tragic Tale of Love and Zombies
 - Redeeming Love
 - Poses for Artists Volume 1 - Dynamic and Sitting Poses: An Essential Reference for Figure Drawing and the Human Form
 - Poems That Make Grown Women Cry
 - Nightingale, Sing
 - Night Sky with Exit Wounds
 - Mrs. Houdini

Page 10: Found 20 books
 - Modern Romance
 - Miss Peregrineâs Home for Peculiar Children (Miss Peregrineâs Peculiar Children #1)
 - Louisa: The Extraordinary Life of Mrs. Adams
 - Little Red
 - Library of Souls (Miss Peregrineâs Peculiar Children #3)
 - Large Print Heart of the Pride
 - I Had a Nice Time And Other Lies...: How to find love & sh*t like that
 - Hollow City (Miss Peregrineâs Peculiar Children #2)
 - Grumbles
 - Full Moon over Noahâs Ark: An Odyssey to Mount Ararat and Beyond
 - Frostbite (Vampire Academy #2)
 - Follow You Home
 - First Steps for New Christians (Print Edition)
 - Finders Keepers (Bill Hodges Trilogy #2)
 - Fables, Vol. 1: Legends in Exile (Fables #1)
 - Eureka Trivia 6.0
 - Drive: The Surprising Truth About What Motivates Us
 - Done Rubbed Out (Reightman & Bailey #1)
 - Doing It Over (Most Likely To #1)
 - Deliciously Ella Every Day: Quick and Easy Recipes for Gluten-Free Snacks, Packed Lunches, and Simple Meals

Page 11: Found 20 books
 - Dark Notes
 - Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead
 - Close to You
 - Chasing Heaven: What Dying Taught Me About Living
 - Big Magic: Creative Living Beyond Fear
 - Becoming Wise: An Inquiry into the Mystery and Art of Living
 - Beauty Restored (Riley Family Legacy Novellas #3)
 - Batman: The Long Halloween (Batman)
 - Batman: The Dark Knight Returns (Batman)
 - Ayumi's Violin
 - Anonymous
 - Amy Meets the Saints and Sages
 - Amid the Chaos
 - Amatus
 - Agnostic: A Spirited Manifesto
 - Zealot: The Life and Times of Jesus of Nazareth
 - You (You #1)
 - Wonder Woman: Earth One, Volume One (Wonder Woman: Earth One #1)
 - Wild Swans
 - Why the Right Went Wrong: Conservatism--From Goldwater to the Tea Party and Beyond

Page 12: Found 20 books
 - Whole Lotta Creativity Going On: 60 Fun and Unusual Exercises to Awaken and Strengthen Your Creativity
 - What's It Like in Space?: Stories from Astronauts Who've Been There
 - We Are Robin, Vol. 1: The Vigilante Business (We Are Robin #1)
 - Walt Disney's Alice in Wonderland
 - V for Vendetta (V for Vendetta Complete)
 - Until Friday Night (The Field Party #1)
 - Unbroken: A World War II Story of Survival, Resilience, and Redemption
 - Twenty Yawns
 - Through the Woods
 - This Is Where It Ends
 - The Year of Magical Thinking
 - The Wright Brothers
 - The White Queen (The Cousins' War #1)
 - The Wedding Pact (The O'Malleys #2)
 - The Time Keeper
 - The Testament of Mary
 - The Star-Touched Queen
 - The Songs of the Gods
 - The Song of Achilles
 - The Rosie Project (Don Tillman #1)

Page 13: Found 20 books
 - The Power of Habit: Why We Do What We Do in Life and Business
 - The Marriage of Opposites
 - The Lucifer Effect: Understanding How Good People Turn Evil
 - The Long Haul (Diary of a Wimpy Kid #9)
 - The Loney
 - The Literature Book (Big Ideas Simply Explained)
 - The Last Mile (Amos Decker #2)
 - The Immortal Life of Henrietta Lacks
 - The Hidden Oracle (The Trials of Apollo #1)
 - The Help Yourself Cookbook for Kids: 60 Easy Plant-Based Recipes Kids Can Make to Stay Healthy and Save the Earth
 - The Guilty (Will Robie #4)
 - The First Hostage (J.B. Collins #2)
 - The Dovekeepers
 - The Darkest Lie
 - The Bane Chronicles (The Bane Chronicles #1-11)
 - The Bad-Ass Librarians of Timbuktu: And Their Race to Save the Worldâs Most Precious Manuscripts
 - The 14th Colony (Cotton Malone #11)
 - That Darkness (Gardiner and Renner #1)
 - Tastes Like Fear (DI Marnie Rome #3)
 - Take Me with You

Page 14: Found 20 books
 - Swell: A Year of Waves
 - Superman Vol. 1: Before Truth (Superman by Gene Luen Yang #1)
 - Still Life with Bread Crumbs
 - Steve Jobs
 - Sorting the Beef from the Bull: The Science of Food Fraud Forensics
 - Someone Like You (The Harrisons #2)
 - So Cute It Hurts!!, Vol. 6 (So Cute It Hurts!! #6)
 - Shtum
 - See America: A Celebration of Our National Parks & Treasured Sites
 - salt.
 - Robin War
 - Red Hood/Arsenal, Vol. 1: Open for Business (Red Hood/Arsenal #1)
 - Rain Fish
 - Quarter Life Poetry: Poems for the Young, Broke and Hangry
 - Pet Sematary
 - Overload: How to Unplug, Unwind, and Unleash Yourself from the Pressure of Stress
 - Once Was a Time
 - Old School (Diary of a Wimpy Kid #10)
 - No Dream Is Too High: Life Lessons From a Man Who Walked on the Moon
 - Naruto (3-in-1 Edition), Vol. 14: Includes Vols. 40, 41 & 42 (Naruto: Omnibus #14)

Page 15: Found 20 books
 - My Name Is Lucy Barton
 - My Mrs. Brown
 - My Kind of Crazy
 - Mr. Mercedes (Bill Hodges Trilogy #1)
 - More Than Music (Chasing the Dream #1)
 - Made to Stick: Why Some Ideas Survive and Others Die
 - Luis Paints the World
 - Luckiest Girl Alive
 - Lowriders to the Center of the Earth (Lowriders in Space #2)
 - Love Is a Mix Tape (Music #1)
 - Looking for Lovely: Collecting the Moments that Matter
 - Living Leadership by Insight: A Good Leader Achieves, a Great Leader Builds Monuments
 - Let It Out: A Journey Through Journaling
 - Lady Midnight (The Dark Artifices #1)
 - It's All Easy: Healthy, Delicious Weeknight Meals in under 30 Minutes
 - Island of Dragons (Unwanteds #7)
 - I Know What I'm Doing -- and Other Lies I Tell Myself: Dispatches from a Life Under Construction
 - I Am Pilgrim (Pilgrim #1)
 - Hyperbole and a Half: Unfortunate Situations, Flawed Coping Mechanisms, Mayhem, and Other Things That Happened
 - Hush, Hush (Hush, Hush #1)

Page 16: Found 20 books
 - Hold Your Breath (Search and Rescue #1)
 - Hamilton: The Revolution
 - Greek Mythic History
 - God: The Most Unpleasant Character in All Fiction
 - Glory over Everything: Beyond The Kitchen House
 - Feathers: Displays of Brilliant Plumage
 - Far & Away: Places on the Brink of Change: Seven Continents, Twenty-Five Years
 - Every Last Word
 - Eligible (The Austen Project #4)
 - El Deafo
 - Eight Hundred Grapes
 - Eaternity: More than 150 Deliciously Easy Vegan Recipes for a Long, Healthy, Satisfied, Joyful Life
 - Eat Fat, Get Thin
 - Don't Get Caught
 - Doctor Sleep (The Shining #2)
 - Demigods & Magicians: Percy and Annabeth Meet the Kanes (Percy Jackson & Kane Chronicles Crossover #1-3)
 - Dear Mr. Knightley
 - Daily Fantasy Sports
 - Crazy Love: Overwhelmed by a Relentless God
 - Cometh the Hour (The Clifton Chronicles #6)

Page 17: Found 20 books
 - Code Name Verity (Code Name Verity #1)
 - Clockwork Angel (The Infernal Devices #1)
 - City of Glass (The Mortal Instruments #3)
 - City of Fallen Angels (The Mortal Instruments #4)
 - City of Bones (The Mortal Instruments #1)
 - City of Ashes (The Mortal Instruments #2)
 - Cell
 - Catching Jordan (Hundred Oaks)
 - Carry On, Warrior: Thoughts on Life Unarmed
 - Carrie
 - Buying In: The Secret Dialogue Between What We Buy and Who We Are
 - Brain on Fire: My Month of Madness
 - Batman: Europa
 - Barefoot Contessa Back to Basics
 - Barefoot Contessa at Home: Everyday Recipes You'll Make Over and Over Again
 - Balloon Animals
 - Art Ops Vol. 1
 - Aristotle and Dante Discover the Secrets of the Universe (Aristotle and Dante Discover the Secrets of the Universe #1)
 - Angels Walking (Angels Walking #1)
 - Angels & Demons (Robert Langdon #1)

Page 18: Found 20 books
 - All the Light We Cannot See
 - Adulthood Is a Myth: A "Sarah's Scribbles" Collection
 - Abstract City
 - A Time of Torment (Charlie Parker #14)
 - A Study in Scarlet (Sherlock Holmes #1)
 - A Series of Catastrophes and Miracles: A True Story of Love, Science, and Cancer
 - A People's History of the United States
 - A Man Called Ove
 - A Distant Mirror: The Calamitous 14th Century
 - A Brush of Wings (Angels Walking #3)
 - 1491: New Revelations of the Americas Before Columbus
 - The Three Searches, Meaning, and the Story
 - Searching for Meaning in Gailana
 - Rook
 - My Kitchen Year: 136 Recipes That Saved My Life
 - 13 Hours: The Inside Account of What Really Happened In Benghazi
 - Will You Won't You Want Me?
 - Tipping Point for Planet Earth: How Close Are We to the Edge?
 - The Star-Touched Queen
 - The Silent Sister (Riley MacPherson #1)

Page 19: Found 20 books
 - The Midnight Watch: A Novel of the Titanic and the Californian
 - The Lonely City: Adventures in the Art of Being Alone
 - The Gray Rhino: How to Recognize and Act on the Obvious Dangers We Ignore
 - The Golden Condom: And Other Essays on Love Lost and Found
 - The Epidemic (The Program 0.6)
 - The Dinner Party
 - The Diary of a Young Girl
 - The Children
 - Stars Above (The Lunar Chronicles #4.5)
 - Snatched: How A Drug Queen Went Undercover for the DEA and Was Kidnapped By Colombian Guerillas
 - Raspberry Pi Electronics Projects for the Evil Genius
 - Quench Your Own Thirst: Business Lessons Learned Over a Beer or Two
 - Psycho: Sanitarium (Psycho #1.5)
 - Poisonous (Max Revere Novels #3)
 - One with You (Crossfire #5)
 - No Love Allowed (Dodge Cove #1)
 - Murder at the 42nd Street Library (Raymond Ambler #1)
 - Most Wanted
 - Love, Lies and Spies
 - How to Speak Golf: An Illustrated Guide to Links Lingo

Page 20: Found 20 books
 - Hide Away (Eve Duncan #20)
 - Furiously Happy: A Funny Book About Horrible Things
 - Everyday Italian: 125 Simple and Delicious Recipes
 - Equal Is Unfair: America's Misguided Fight Against Income Inequality
 - Eleanor & Park
 - Dirty (Dive Bar #1)
 - Can You Keep a Secret? (Fear Street Relaunch #4)
 - Boar Island (Anna Pigeon #19)
 - A Paris Apartment
 - A la Mode: 120 Recipes in 60 Pairings: Pies, Tarts, Cakes, Crisps, and More Topped with Ice Cream, Gelato, Frozen Custard, and More
 - Troublemaker: Surviving Hollywood and Scientology
 - The Widow
 - The Sleep Revolution: Transforming Your Life, One Night at a Time
 - The Improbability of Love
 - The Art of Startup Fundraising
 - Take Me Home Tonight (Rock Star Romance #3)
 - Sleeping Giants (Themis Files #1)
 - Setting the World on Fire: The Brief, Astonishing Life of St. Catherine of Siena
 - Playing with Fire
 - Off the Hook (Fishing for Trouble #1)

Page 21: Found 20 books
 - Mothering Sunday
 - Mother, Can You Not?
 - M Train
 - Lilac Girls
 - Lies and Other Acts of Love
 - Lab Girl
 - Keep Me Posted
 - It Didn't Start with You: How Inherited Family Trauma Shapes Who We Are and How to End the Cycle
 - Grey (Fifty Shades #4)
 - Exit, Pursued by a Bear
 - Daredevils
 - Cravings: Recipes for What You Want to Eat
 - Born for This: How to Find the Work You Were Meant to Do
 - Arena
 - Adultery
 - A Mother's Reckoning: Living in the Aftermath of Tragedy
 - A Gentleman's Position (Society of Gentlemen #3)
 - 11/22/63
 - 10% Happier: How I Tamed the Voice in My Head, Reduced Stress Without Losing My Edge, and Found Self-Help That Actually Works
 - 10-Day Green Smoothie Cleanse: Lose Up to 15 Pounds in 10 Days!

Page 22: Found 20 books
 - Without Shame
 - Watchmen
 - Unlimited Intuition Now
 - Underlying Notes
 - The Shack
 - The New Brand You: Your New Image Makes the Sale for You
 - The Moosewood Cookbook: Recipes from Moosewood Restaurant, Ithaca, New York
 - The Flowers Lied

In [ ]:
for i in soup.find_all('a'):
  print(i.text.strip())

Books to Scrape
Home
Books
Travel
Mystery
Historical Fiction
Sequential Art
Classics
Philosophy
Romance
Womens Fiction
Fiction
Childrens
Religion
Nonfiction
Music
Default
Science Fiction
Sports and Games
Add a comment
Fantasy
New Adult
Young Adult
Science
Poetry
Paranormal
Art
Psychology
Autobiography
Parenting
Adult Fiction
Humor
Horror
History
Food and Drink
Christian Fiction
Business
Biography
Thriller
Contemporary
Spirituality
Academic
Self Help
Historical
Christian
Suspense
Short Stories
Novels
Health
Politics
Cultural
Erotica
Crime

Frankenstein

Forever Rockers (The Rocker ...

Fighting Fate (Fighting #6)

Emma

Eat, Pray, Love

Deep Under (Walker Security ...

Choosing Our Religion: The ...

Charlie and the Chocolate ...

Charity's Cross (Charles Towne ...

Bright Lines

Bridget Jones's Diary (Bridget ...

Bounty (Colorado Mountain #7)

Blood Defense (Samantha Brinkman ...

Bleach, Vol. 1: Strawberry ...

Beyond Good and Evil

Alice in Wonderland (Alice's ...

Ajin: Demi-Human, Volume 1 ...

A Spy's Devotion (The ...

1st to Die (Women's ...

1,000 Places to See ...
previous

# Step 4:
Locate elements using tags, classes, or CSS selectors

In [ ]:
# STEP 4: Select containers for each item
cards = soup.select("article.product_pod")

In [ ]:
rows = []
rating_map = {"One":1, "Two":2, "Three":3, "Four":4, "Five":5}

# Step 5:
Repeat process for all required data

In [ ]:
import re
# Regular expression, remove symbols, extract digits, filter URLs, etc
rows = []
for card in cards:
    title = card.h3.a.get("title", "").strip()

    # --- clean price ---
    price_text = card.select_one(".price_color").get_text(strip=True)
    clean_price = re.sub(r"[^\d.]", "", price_text)   # removes £, Â, etc.
    price = float(clean_price) if clean_price else None

    # rating
    rating_word = card.select_one("p.star-rating")["class"][1]
    rating = rating_map.get(rating_word, None)

    # availability
    availability = card.select_one(".instock.availability").get_text(strip=True)

    # append row (no URL)
    rows.append({
        "title": title,
        "price_gbp": price,
        "rating": rating,
        "availability": availability
    })

# Step 6:
Save your file in required format

In [ ]:
# STEP 5: Convert to DataFrame
df = pd.DataFrame(rows)
print(df.head())

# STEP 6: Save output
df.to_csv("books_page1.csv", index=False)

                              title  price_gbp  rating availability
0                      Frankenstein      38.00       2     In stock
1  Forever Rockers (The Rocker #12)      28.80       3     In stock
2       Fighting Fate (Fighting #6)      39.24       3     In stock
3                              Emma      32.93       2     In stock
4                   Eat, Pray, Love      51.32       3     In stock

# Step 7:
Repeat above steps for many pages or use loop

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import os

# Base URL of the website
base_url = 'https://books.toscrape.com/catalogue/page-{}.html'
book_base_url = 'https://books.toscrape.com/catalogue/'

# Create directories if they don't exist
os.makedirs('data_sheet', exist_ok=True)
os.makedirs('images', exist_ok=True)

# List to store book details
books = []

# Function to extract data from a single page
def extract_data_from_page(soup, page):
    for book in soup.find_all('article', class_='product_pod'):
        title = book.h3.a['title']
        price = book.find('p', class_='price_color').text
        availability = book.find('p', class_='instock availability').text.strip()
        rating_text = book.p['class'][1]
        rating = convert_rating_to_number(rating_text)
        link = book_base_url + book.h3.a['href']
        thumbnail_url = 'https://books.toscrape.com/' + book.find('img', class_='thumbnail')['src']
        thumbnail_file_name = save_thumbnail_image(thumbnail_url, title)

        book_data = {
            'Title': title,
            'Price': price,
            'Availability': availability,
            'Rating': rating,
            'Link': link,
            'Thumbnail URL': thumbnail_url,
            'Thumbnail File Name': thumbnail_file_name
        }

        books.append(book_data)

        # Print the extracted data to the console in a formatted way
        print(f"Page: {page}")
        print(f"Title: {title}")
        print(f"Price: {price}")
        print(f"Availability: {availability}")
        print(f"Rating: {rating}")
        print(f"Link: {link}")
        print(f"Thumbnail URL: {thumbnail_url}")
        print(f"Thumbnail File Name: {thumbnail_file_name}")
        print("="*50)

# Function to convert rating text to a number
def convert_rating_to_number(rating_text):
    rating_dict = {
        'One': 1,
        'Two': 2,
        'Three': 3,
        'Four': 4,
        'Five': 5
    }
    return rating_dict.get(rating_text, 0)

# Function to save thumbnail image
def save_thumbnail_image(url, title):
    response = requests.get(url)
    sanitized_title = "".join([c if c.isalnum() else "_" for c in title])
    image_path = os.path.join('images', f"{sanitized_title}.jpg")
    with open(image_path, 'wb') as file:
        file.write(response.content)
    return image_path

# Loop through the first 10 pages
for page in range(1, 51):  # Scraping the first 10 pages
    url = base_url.format(page)
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    extract_data_from_page(soup, page)
    print(f"Extracted data from page {page}")

# Save the data to a CSV file
df = pd.DataFrame(books)
df.to_csv('data_sheet/books_data.csv', index=False)
print("Data saved to data_sheet/books_data.csv")

Page: 1
Title: A Light in the Attic
Price: £51.77
Availability: In stock
Rating: 3
Link: https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg
Thumbnail File Name: images/A_Light_in_the_Attic.jpg
==================================================
Page: 1
Title: Tipping the Velvet
Price: £53.74
Availability: In stock
Rating: 1
Link: https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg
Thumbnail File Name: images/Tipping_the_Velvet.jpg
==================================================
Page: 1
Title: Soumission
Price: £50.10
Availability: In stock
Rating: 1
Link: https://books.toscrape.com/catalogue/soumission_998/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg
Thumbnail File Name: images/Soumission.jpg
==================================================
Page: 1
Title: Sharp Objects
Price: £47.82
Availability: In stock
Rating: 4
Link: https://books.toscrape.com/catalogue/sharp-objects_997/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg
Thumbnail File Name: images/Sharp_Objects.jpg
==================================================
Page: 1
Title: Sapiens: A Brief History of Humankind
Price: £54.23
Availability: In stock
Rating: 5
Link: https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg
Thumbnail File Name: images/Sapiens__A_Brief_History_of_Humankind.jpg
==================================================
Page: 1
Title: The Requiem Red
Price: £22.65
Availability: In stock
Rating: 1
Link: https://books.toscrape.com/catalogue/the-requiem-red_995/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg
Thumbnail File Name: images/The_Requiem_Red.jpg
==================================================
Page: 1
Title: The Dirty Little Secrets of Getting Your Dream Job
Price: £33.34
Availability: In stock
Rating: 4
Link: https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg
Thumbnail File Name: images/The_Dirty_Little_Secrets_of_Getting_Your_Dream_Job.jpg
==================================================
Page: 1
Title: The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
Price: £17.93
Availability: In stock
Rating: 3
Link: https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg
Thumbnail File Name: images/The_Coming_Woman__A_Novel_Based_on_the_Life_of_the_Infamous_Feminist__Victoria_Woodhull.jpg
==================================================
Page: 1
Title: The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
Price: £22.60
Availability: In stock
Rating: 4
Link: https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg
Thumbnail File Name: images/The_Boys_in_the_Boat__Nine_Americans_and_Their_Epic_Quest_for_Gold_at_the_1936_Berlin_Olympics.jpg
==================================================
Page: 1
Title: The Black Maria
Price: £52.15
Availability: In stock
Rating: 1
Link: https://books.toscrape.com/catalogue/the-black-maria_991/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/58/46/5846057e28022268153beff6d352b06c.jpg
Thumbnail File Name: images/The_Black_Maria.jpg
==================================================
Page: 1
Title: Starving Hearts (Triangular Trade Trilogy, #1)
Price: £13.99
Availability: In stock
Rating: 2
Link: https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg
Thumbnail File Name: images/Starving_Hearts__Triangular_Trade_Trilogy___1_.jpg
==================================================
Page: 1
Title: Shakespeare's Sonnets
Price: £20.66
Availability: In stock
Rating: 4
Link: https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg
Thumbnail File Name: images/Shakespeare_s_Sonnets.jpg
==================================================
Page: 1
Title: Set Me Free
Price: £17.46
Availability: In stock
Rating: 5
Link: https://books.toscrape.com/catalogue/set-me-free_988/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg
Thumbnail File Name: images/Set_Me_Free.jpg
==================================================
Page: 1
Title: Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Price: £52.29
Availability: In stock
Rating: 5
Link: https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg
Thumbnail File Name: images/Scott_Pilgrim_s_Precious_Little_Life__Scott_Pilgrim__1_.jpg
==================================================
Page: 1
Title: Rip it Up and Start Again
Price: £35.02
Availability: In stock
Rating: 5
Link: https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg
Thumbnail File Name: images/Rip_it_Up_and_Start_Again.jpg
==================================================
Page: 1
Title: Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Price: £57.25
Availability: In stock
Rating: 3
Link: https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg
Thumbnail File Name: images/Our_Band_Could_Be_Your_Life__Scenes_from_the_American_Indie_Underground__1981_1991.jpg
==================================================
Page: 1
Title: Olio
Price: £23.88
Availability: In stock
Rating: 1
Link: https://books.toscrape.com/catalogue/olio_984/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg
Thumbnail File Name: images/Olio.jpg
==================================================
Page: 1
Title: Mesaerion: The Best Science Fiction Stories 1800-1849
Price: £37.59
Availability: In stock
Rating: 1
Link: https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg
Thumbnail File Name: images/Mesaerion__The_Best_Science_Fiction_Stories_1800_1849.jpg
==================================================
Page: 1
Title: Libertarianism for Beginners
Price: £51.33
Availability: In stock
Rating: 2
Link: https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg
Thumbnail File Name: images/Libertarianism_for_Beginners.jpg
==================================================
Page: 1
Title: It's Only the Himalayas
Price: £45.17
Availability: In stock
Rating: 2
Link: https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg
Thumbnail File Name: images/It_s_Only_the_Himalayas.jpg
==================================================
Extracted data from page 1
Page: 2
Title: In Her Wake
Price: £12.84
Availability: In stock
Rating: 1
Link: https://books.toscrape.com/catalogue/in-her-wake_980/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/5d/72/5d72709c6a7a9584a4d1cf07648bfce1.jpg
Thumbnail File Name: images/In_Her_Wake.jpg
==================================================
Page: 2
Title: How Music Works
Price: £37.32
Availability: In stock
Rating: 2
Link: https://books.toscrape.com/catalogue/how-music-works_979/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/5c/c8/5cc8e107246cb478960d4f0aba1e1c8e.jpg
Thumbnail File Name: images/How_Music_Works.jpg
==================================================
Page: 2
Title: Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More
Price: £30.52
Availability: In stock
Rating: 3
Link: https://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/9f/59/9f59f01fa916a7bb8f0b28a4012179a4.jpg
Thumbnail File Name: images/Foolproof_Preserving__A_Guide_to_Small_Batch_Jams__Jellies__Pickles__Condiments__and_More__A_Foolproof_Guide_to_Making_Small_Batch_Jams__Jellies__Pickles__Condiments__and_More.jpg
==================================================
Page: 2
Title: Chase Me (Paris Nights #2)
Price: £25.27
Availability: In stock
Rating: 5
Link: https://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994fd3d1c1a.jpg
Thumbnail File Name: images/Chase_Me__Paris_Nights__2_.jpg
==================================================
Page: 2
Title: Black Dust
Price: £34.53
Availability: In stock
Rating: 5
Link: https://books.toscrape.com/catalogue/black-dust_976/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4ef25787.jpg
Thumbnail File Name: images/Black_Dust.jpg
==================================================
Page: 2
Title: Birdsong: A Story in Pictures
Price: £54.64
Availability: In stock
Rating: 3
Link: https://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/af/6e/af6e796160fe63e0cf19d44395c7ddf2.jpg
Thumbnail File Name: images/Birdsong__A_Story_in_Pictures.jpg
==================================================
Page: 2
Title: America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana
Price: £22.50
Availability: In stock
Rating: 3
Link: https://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/ef/0b/ef0bed08de4e083dba5e20fdb98d9c36.jpg
Thumbnail File Name: images/America_s_Cradle_of_Quarterbacks__Western_Pennsylvania_s_Football_Factory_from_Johnny_Unitas_to_Joe_Montana.jpg
==================================================
Page: 2
Title: Aladdin and His Wonderful Lamp
Price: £53.13
Availability: In stock
Rating: 3
Link: https://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/d6/da/d6da0371958068bbaf39ea9c174275cd.jpg
Thumbnail File Name: images/Aladdin_and_His_Wonderful_Lamp.jpg
==================================================
Page: 2
Title: Worlds Elsewhere: Journeys Around Shakespeare’s Globe
Price: £40.30
Availability: In stock
Rating: 5
Link: https://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/2e/98/2e98c332bf8563b584784971541c4445.jpg
Thumbnail File Name: images/Worlds_Elsewhere__Journeys_Around_Shakespeare_s_Globe.jpg
==================================================
Page: 2
Title: Wall and Piece
Price: £44.18
Availability: In stock
Rating: 4
Link: https://books.toscrape.com/catalogue/wall-and-piece_971/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/a5/41/a5416b9646aaa7287baa287ec2590270.jpg
Thumbnail File Name: images/Wall_and_Piece.jpg
==================================================
Page: 2
Title: The Four Agreements: A Practical Guide to Personal Freedom
Price: £17.66
Availability: In stock
Rating: 5
Link: https://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/0f/7e/0f7ee69495c0df1d35723f012624a9f8.jpg
Thumbnail File Name: images/The_Four_Agreements__A_Practical_Guide_to_Personal_Freedom.jpg
==================================================
Page: 2
Title: The Five Love Languages: How to Express Heartfelt Commitment to Your Mate
Price: £31.05
Availability: In stock
Rating: 3
Link: https://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/38/c5/38c56fba316c07305643a8065269594e.jpg
Thumbnail File Name: images/The_Five_Love_Languages__How_to_Express_Heartfelt_Commitment_to_Your_Mate.jpg
==================================================
Page: 2
Title: The Elephant Tree
Price: £23.82
Availability: In stock
Rating: 5
Link: https://books.toscrape.com/catalogue/the-elephant-tree_968/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/5d/7e/5d7ecde8e81513eba8a64c9fe000744b.jpg
Thumbnail File Name: images/The_Elephant_Tree.jpg
==================================================
Page: 2
Title: The Bear and the Piano
Price: £36.89
Availability: In stock
Rating: 1
Link: https://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/cf/bb/cfbb5e62715c6d888fd07794c9bab5d6.jpg
Thumbnail File Name: images/The_Bear_and_the_Piano.jpg
==================================================
Page: 2
Title: Sophie's World
Price: £15.94
Availability: In stock
Rating: 5
Link: https://books.toscrape.com/catalogue/sophies-world_966/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/65/71/6571919836ec51ed54f0050c31d8a0cd.jpg
Thumbnail File Name: images/Sophie_s_World.jpg
==================================================
Page: 2
Title: Penny Maybe
Price: £33.29
Availability: In stock
Rating: 3
Link: https://books.toscrape.com/catalogue/penny-maybe_965/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/12/53/1253c21c5ef3c6d075c5fa3f5fecee6a.jpg
Thumbnail File Name: images/Penny_Maybe.jpg
==================================================
Page: 2
Title: Maude (1883-1993):She Grew Up with the country
Price: £18.02
Availability: In stock
Rating: 2
Link: https://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/f5/88/f5889d038f5d8e949b494d147c2dcf54.jpg
Thumbnail File Name: images/Maude__1883_1993__She_Grew_Up_with_the_country.jpg
==================================================
Page: 2
Title: In a Dark, Dark Wood
Price: £19.63
Availability: In stock
Rating: 1
Link: https://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/23/85/238570a1c284e730dbc737a7e631ae2b.jpg
Thumbnail File Name: images/In_a_Dark__Dark_Wood.jpg
==================================================
Page: 2
Title: Behind Closed Doors
Price: £52.22
Availability: In stock
Rating: 4
Link: https://books.toscrape.com/catalogue/behind-closed-doors_962/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/e1/5c/e15c289ba58cea38519e1281e859f0c1.jpg
Thumbnail File Name: images/Behind_Closed_Doors.jpg
==================================================
Page: 2
Title: You can't bury them all: Poems
Price: £33.63
Availability: In stock
Rating: 2
Link: https://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/e9/20/e9203b733126c4a0832a1c7885dc27cf.jpg
Thumbnail File Name: images/You_can_t_bury_them_all__Poems.jpg
==================================================
Extracted data from page 2
Page: 3
Title: Slow States of Collapse: Poems
Price: £57.31
Availability: In stock
Rating: 3
Link: https://books.toscrape.com/catalogue/slow-states-of-collapse-poems_960/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/72/41/72417db983862010ef0c1a25de98c7d7.jpg
Thumbnail File Name: images/Slow_States_of_Collapse__Poems.jpg
==================================================
Page: 3
Title: Reasons to Stay Alive
Price: £26.41
Availability: In stock
Rating: 2
Link: https://books.toscrape.com/catalogue/reasons-to-stay-alive_959/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/cb/bd/cbbdb0222ee8a0f6ab61657412a15794.jpg
Thumbnail File Name: images/Reasons_to_Stay_Alive.jpg
==================================================
Page: 3
Title: Private Paris (Private #10)
Price: £47.61
Availability: In stock
Rating: 5
Link: https://books.toscrape.com/catalogue/private-paris-private-10_958/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/9d/05/9d0533bae1578846d728a82913b95c26.jpg
Thumbnail File Name: images/Private_Paris__Private__10_.jpg
==================================================
Page: 3
Title: #HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.
Price: £23.11
Availability: In stock
Rating: 5
Link: https://books.toscrape.com/catalogue/higherselfie-wake-up-your-life-free-your-soul-find-your-tribe_957/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/9c/46/9c463c7631c82401160fd3b554b8f0e1.jpg
Thumbnail File Name: images/_HigherSelfie__Wake_Up_Your_Life__Free_Your_Soul__Find_Your_Tribe_.jpg
==================================================
Page: 3
Title: Without Borders (Wanderlove #1)
Price: £45.07
Availability: In stock
Rating: 2
Link: https://books.toscrape.com/catalogue/without-borders-wanderlove-1_956/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/24/e2/24e2f5c9d325c4004d8190c054da86dd.jpg
Thumbnail File Name: images/Without_Borders__Wanderlove__1_.jpg
==================================================
Page: 3
Title: When We Collided
Price: £31.77
Availability: In stock
Rating: 1
Link: https://books.toscrape.com/catalogue/when-we-collided_955/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/08/04/08044269fc197645268a6197c57e6173.jpg
Thumbnail File Name: images/When_We_Collided.jpg
==================================================
Page: 3
Title: We Love You, Charlie Freeman
Price: £50.27
Availability: In stock
Rating: 5
Link: https://books.toscrape.com/catalogue/we-love-you-charlie-freeman_954/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/5f/15/5f152afdbc42356ecba02f61058a7e5b.jpg
Thumbnail File Name: images/We_Love_You__Charlie_Freeman.jpg
==================================================
Page: 3
Title: Untitled Collection: Sabbath Poems 2014
Price: £14.27
Availability: In stock
Rating: 4
Link: https://books.toscrape.com/catalogue/untitled-collection-sabbath-poems-2014_953/index.html
Thumbnail URL: https://books.toscrape.com/../media/cache/f9/3b/f93b4a650f03a5d21f2436d7813f42c2.jpg
Thumbnail File Name: images/Untitled_Collection__Sabbath_Poems_2014.jpg
==================================================
Page: 3

In [ ]:
df = pd.read_csv('/content/data_sheet/books_data.csv')
df

,Title,Price,Availability,Rating,Link,Thumbnail URL,Thumbnail File Name
0,A Light in the Attic,£51.77,In stock,3,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/../media/cache/2c/d...,images/A_Light_in_the_Attic.jpg
1,Tipping the Velvet,£53.74,In stock,1,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/../media/cache/26/0...,images/Tipping_the_Velvet.jpg
2,Soumission,£50.10,In stock,1,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/../media/cache/3e/e...,images/Soumission.jpg
3,Sharp Objects,£47.82,In stock,4,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/../media/cache/32/5...,images/Sharp_Objects.jpg
4,Sapiens: A Brief History of Humankind,£54.23,In stock,5,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/../media/cache/be/a...,images/Sapiens__A_Brief_History_of_Humankind.jpg
...,...,...,...,...,...,...,...
195,Eureka Trivia 6.0,£54.59,In stock,4,https://books.toscrape.com/catalogue/eureka-tr...,https://books.toscrape.com/../media/cache/96/1...,images/Eureka_Trivia_6_0.jpg
196,Drive: The Surprising Truth About What Motivat...,£34.95,In stock,4,https://books.toscrape.com/catalogue/drive-the...,https://books.toscrape.com/../media/cache/8a/4...,images/Drive__The_Surprising_Truth_About_What_...
197,Done Rubbed Out (Reightman & Bailey #1),£37.72,In stock,5,https://books.toscrape.com/catalogue/done-rubb...,https://books.toscrape.com/../media/cache/08/4...,images/Done_Rubbed_Out__Reightman___Bailey__1_...
198,Doing It Over (Most Likely To #1),£35.61,In stock,3,https://books.toscrape.com/catalogue/doing-it-...,https://books.toscrape.com/../media/cache/e9/2...,images/Doing_It_Over__Most_Likely_To__1_.jpg
199,Deliciously Ella Every Day: Quick and Easy Rec...,£42.16,In stock,3,https://books.toscrape.com/catalogue/delicious...,https://books.toscrape.com/../media/cache/20/f...,images/Deliciously_Ella_Every_Day__Quick_and_E...

In [ ]:
df=pd.read_csv('')

,Title,Price,Availability,Rating,Link,Thumbnail URL,Thumbnail File Name
0,A Light in the Attic,£51.77,In stock,3,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/../media/cache/2c/d...,images/A_Light_in_the_Attic.jpg
1,Tipping the Velvet,£53.74,In stock,1,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/../media/cache/26/0...,images/Tipping_the_Velvet.jpg
2,Soumission,£50.10,In stock,1,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/../media/cache/3e/e...,images/Soumission.jpg
3,Sharp Objects,£47.82,In stock,4,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/../media/cache/32/5...,images/Sharp_Objects.jpg
4,Sapiens: A Brief History of Humankind,£54.23,In stock,5,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/../media/cache/be/a...,images/Sapiens__A_Brief_History_of_Humankind.jpg
...,...,...,...,...,...,...,...
195,Eureka Trivia 6.0,£54.59,In stock,4,https://books.toscrape.com/catalogue/eureka-tr...,https://books.toscrape.com/../media/cache/96/1...,images/Eureka_Trivia_6_0.jpg
196,Drive: The Surprising Truth About What Motivat...,£34.95,In stock,4,https://books.toscrape.com/catalogue/drive-the...,https://books.toscrape.com/../media/cache/8a/4...,images/Drive__The_Surprising_Truth_About_What_...
197,Done Rubbed Out (Reightman & Bailey #1),£37.72,In stock,5,https://books.toscrape.com/catalogue/done-rubb...,https://books.toscrape.com/../media/cache/08/4...,images/Done_Rubbed_Out__Reightman___Bailey__1_...
198,Doing It Over (Most Likely To #1),£35.61,In stock,3,https://books.toscrape.com/catalogue/doing-it-...,https://books.toscrape.com/../media/cache/e9/2...,images/Doing_It_Over__Most_Likely_To__1_.jpg
199,Deliciously Ella Every Day: Quick and Easy Rec...,£42.16,In stock,3,https://books.toscrape.com/catalogue/delicious...,https://books.toscrape.com/../media/cache/20/f...,images/Deliciously_Ella_Every_Day__Quick_and_E...